ALTER TABLE missing_dem_tiles ADD COLUMN absolutepath text, ADD COLUMN project text, ADD COLUMN srid_orig integer, ADD COLUMN srid integer, ADD COLUMN pixeltype text, ADD COLUMN x float, ADD COLUMN y float, ADD COLUMN width integer, ADD COLUMN height integer, ADD COLUMN pixelwidth float, ADD COLUMN pixelheight float;
SELECT AddGeometryColumn('public','missing_dem_tiles','envelope',0,'POLYGON',2) ;
SELECT AddGeometryColumn('public','missing_dem_tiles','envelope_albers',6579,'POLYGON',2) ;
SELECT AddGeometryColumn('public','missing_dem_tiles','centroid',0,'POINT',2) ;
SELECT AddGeometryColumn('public','missing_dem_tiles','centroid_albers',6579,'POINT',2) ;
UPDATE missing_dem_tiles SET project = p.project FROM absolutepaths AS p WHERE missing_dem_tiles.filename = p.filename ;
UPDATE missing_dem_tiles SET absolutepath = p.absolutepath FROM absolutepaths AS p WHERE missing_dem_tiles.filename = p.filename ;
UPDATE missing_dem_tiles SET srid_orig = ST_SRID(rast) ;
UPDATE missing_dem_tiles SET srid = ST_SRID(rast) ;
UPDATE missing_dem_tiles SET pixeltype = ST_BandPixelType(rast) ;
UPDATE missing_dem_tiles SET width = ST_Width(rast) ;
UPDATE missing_dem_tiles SET height = ST_Height(rast) ;
UPDATE missing_dem_tiles SET pixelwidth = ST_PixelWidth(rast) ;
UPDATE missing_dem_tiles SET pixelheight = ST_PixelHeight(rast) ;
